# Generated by Django 5.0.2 on 2024-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
